spring.application.name=FluxGuard

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.palxponyhcjwpdhsobfv&password=fluxguard123@
spring.datasource.username=postgres.palxponyhcjwpdhsobfv
spring.datasource.password=fluxguard123@
